name: WorldShift
description: "A plugin that allows players to change worlds"
author: "jasonwynn10"
version: 1.1.2
main: shift\Main
api:
 - 3.0.0
 - 3.0.0-ALPHA7
load: POSTWORLD
commands:
  world:
    usage: "/world <world> [player]"
    description: "Moves the player between worlds"
    permission: "world.cmd"
  worlds:
    usage: "/worlds"
    description: "List all available worlds worlds"
    permission: "worlds.cmd"
permissions:
  world.cmd:
    default: true
  worlds.cmd:
    default: true