name: RandomEnchant
main: xenialdan\RandomEnchant\Loader
version: 0.1.1
api:
 - 3.0.0
 - 3.0.0-ALPHA7
load: POSTWORLD
author: "XenialDan"
permissions:
  randomenchant:
    description: "Allows the player to get enchantments"
    default: op