name: ChunkLoaders
author: "jasonwynn10"
version: 0.1.0
api:
 - 3.0.0
 - 3.0.0-ALPHA7
main: jasonwynn10\Loader\Main
description: ""
commands:
  chunk:
    usage: "/chunk <save|unsave> <X-coord> <Z-coord> <Level>"
    permission: chunk
    description: "This command allows a user to keep a chunk from being unloaded in a world"
permissions:
  chunk:
    default: op
    children:
      chunk.save:
        default: op
      chunk.unsave:
        default: op