name: CustomAlerts
main: CustomAlerts\CustomAlerts
version: 1.7
api:
- 1.0.0
- 2.0.0
- 2.1.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
load: STARTUP
author: EvolSoft
description: "Customize alerts (join/leave messages, etc...)"
website: "http://www.evolsoft.tk"

commands:
  customalerts:
    aliases: ["calerts"]
    description: CustomAlerts Master Command
    permission: customalerts
permissions:
  customalerts:
    default: op
    description: CustomAlerts Master Permission
    children:
      customalerts.help:
        default: op
        description: CustomAlerts command Help permission.
      customalerts.info:
        default: op
        description: CustomAlerts command Info permission.
      customalerts.reload:
        default: op
        description: CustomAlerts command Reload permission.
