name: HubTP
author: "jasonwynn10"
version: 0.1.1
api:
- 1.0.0
- 2.0.0
- 2.1.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
main: hub\Main
description: ""
commands:
  setBar:
    usage: "/setbar"
    description: "set the default lobby hotbar to look like the player's current one"
    permission: hub.setbar
permissions:
  hub.setbar:
    default: op