name: Sleep4All
description: "One player sleeps for all players!"
author: "jasonwynn10"
version: 0.1.3
api:
 - 3.0.0
 - 3.0.0-ALPHA7
main: sleep\Main
permissions:
    sleep.timechange:
        default: true
