name: WorldEdit
author: "GiantAmethyst"
website: "http://twitter.com/GiantAmethyst"
main: WorldEdit\WorldEdit
description: "An in-game world editor for PMMP PocketMine-MP"
version: 0.1.0
api:
 - 3.0.0
 - 3.0.0-ALPHA7
load: POSTWORLD