name: SafeFly
author: Sean_M
version: "1.0.1"
api:
 - 3.0.0
 - 3.0.0-ALPHA7
description: "Fly in survival without damaging players!"
main: Sean_M\SafeFly\Main

commands:
    fly:
        description: "Activates or deactivates SafeFly."
        usage: "/fly"
        permission: safefly.fly
permissions:
    safefly.fly:
        default: op